name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Hoặc nhánh bạn muốn deploy từ

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set Git author info
        run: |
          git config --global user.email "thanhbinh.bent@gmail.com"
          git config --global user.name "Binh Tran"

      - name: Build & Deploy
        run: npm run deploy:git
